name: ros2   # needed for web-interface

x-ros2-service: &ros2_service
  image: carv:latest
  build:
    context: .
  network_mode: host
  ipc: host

services:

  foxglove:
    <<: *ros2_service
    container_name: foxglove
    command: ros2 run foxglove_bridge foxglove_bridge --ros-args -p port:=21000

  wrapper:
    <<: *ros2_service
    container_name: wrapper
    env_file: ./config/robot.env
    command: ["spot-launch"]
    volumes:
      - ./config:/spot-config:ro

  # reflect_id:
  #   <<: *ros2_service
  #   container_name: reflect_id
  #   command: ros2 launch reflect_id reflect_id.launch.py

  # benchmark:
  #   <<: *ros2_service
  #   container_name: benchmark
  #   profiles: ["benchmark"]
  #   command: ros2 run reflect_id benchmark
